# -*- coding: utf-8 -*-
"""k.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WFa4iv7cD5ui6OCe41S35y8-BFGz8zN
"""

import numpy as np
import pandas as pd
import nibabel as nib
from skimage import feature
import matplotlib.pyplot as plt
from scipy import ndimage as ndi
from skimage.util import random_noise
from scipy import ndimage

1+1